### ISSUE TITLE
CS61A lecture videos

### ISSUE THREAD

**Issue by dshaw002** [abrantesasf/sicp-abrantes-study-guide#1]
Just read through your README.md. I would highly recommend you reference the Brian Harvey Lectures available online at archive.org or Youtube. His videos teach you SICP and are a meta commentary on SICP (because it was originally designed for engineers learning programming and it's easy to get lost if you don't know calculus or engineering). 

I found that his lectures, combined with the homework notes are an amazing way to go through the program. I'm currently on Week 11 of 15 (streams).

Lecture playlist: https://www.youtube.com/watch?v=4leZ1Ca4f0g&list=PLhMnuBfGeCDNgVzLPxF9o5UNKG1b-LFY9
Homework assignments: https://inst.eecs.berkeley.edu/~cs61a/reader/nodate-hw.pdf

**Comment by abrantesasf** [comment]
Hello David, good morning!

First of all, I'm sorry for the delay in responding to your email, but the quarantine due to Covid-19 is causing great disruption in my daily routine.

Thank you very much for your suggestion! I did not know that these lectures were available on the internet.

I will update README.md and include the material you suggested.

Again, thank you very much!

Abrantes

**Comment by abrantesasf** [comment]
Berkeley material added.
